version: "3.8"
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=devpwd
      - MYSQL_DATABASE=notejam
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  notejam:
    build:
      context: ./
      dockerfile: ./docker/local/Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV=dev
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=devpwd
      - DB_NAME=notejam
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
